services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/staticfiles
      - shared_tmp:/tmp
    env_file: .env
    depends_on:
      - postgres
      - redis
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
  
  celery_worker:
    build: .
    env_file: .env
    command: celery -A config worker --loglevel=info
    volumes:
      - shared_tmp:/tmp
    depends_on:
      - web
      - redis

  celery_beat:
    build: .
    env_file: .env
    command: celery -A config beat --loglevel=info
    depends_on:
      - web
      - redis

  postgres:
    image: postgres:17.4-alpine
    container_name: nudetect_postgres
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine3.21
    container_name: nudetect_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  shared_tmp: